var data=[
    {
    "id": 8,
    "cid": 7,
    "code": "P001",
    "title": "Bàn tiếp khách",
    "description": "<p>B&agrave;n tiếp kh&aacute;ch</p>\n",
    "content": "<p>B&agrave;n tiếp kh&aacute;ch</p>\n",
    "image": "http://apixm.devmaster.vn/images/products/phong-khach/001.jpg",
    "metaTitle": "Bàn tiếp khách",
    "metaKeyword": "Bàn tiếp khách",
    "metaDescription": "Bàn tiếp khách",
    "slug": "ban-tiep-khach",
    "priceOld": 12999000,
    "priceNew": 9999000,
    "size": "Size vừa",
    "views": 0,
    "likes": 0,
    "star": null,
    "home": 0,
    "hot": null,
    "createdDate": "2020-07-27T00:00:00",
    "updatedDate": "2020-07-27T17:27:50.89",
    "adminCreated": "4",
    "adminUpdated": "4",
    "status": 1,
    "isdelete": null
    },
    {
    "id": 9,
    "cid": 7,
    "code": "P002",
    "title": "Bàn uống nước 1",
    "description": "<p>B&agrave;n uống nước với thiết kế sang trọng, m&agrave;u sắc tao nh&atilde; ph&ugrave; hợp với mọi kh&ocirc;ng gian ph&ograve;ng kh&aacute;ch trong c&aacute;c căn hộ chung cư hiện đại. B&agrave;n uống nước tại xưởng mộc Ho&agrave;ng Hoan được thiết kế bằng chất liệu gỗ nhập khẩu trực tiếp đem đến trải nghiệm tuyệt vời cho ng&ocirc;i nh&agrave; của bạn.</p>\n",
    "content": "<h1>B&Agrave;N UỐNG NƯỚC - B&Agrave;N TR&Agrave; CAO CẤP CHO CHUNG CƯ</h1>\n\n<p>B&agrave;n uống nước hay b&agrave;n tr&agrave; l&agrave; một trong những sản phẩm kh&ocirc;ng thể thiếu trong mọi ng&ocirc;i nh&agrave; hay trong c&aacute;c căn hộ chung cư, việc lựa chọn b&agrave;n uống nước, b&agrave;n tr&agrave; sao cho ph&ugrave; hợp với kh&ocirc;ng gian , m&agrave;u sắc ph&ograve;ng kh&aacute;ch m&agrave; kh&ocirc;ng ảnh hưởng tới bố cục của căn ph&ograve;ng v&ocirc; c&ugrave;ng quan trọng. Trong b&agrave;i viết n&agrave;y, xưởng mộc Ho&agrave;ng Hoan sẽ c&ugrave;ng c&aacute;c bạn tham khảo một số lưu &yacute; khi lựa chọn b&agrave;n uống nước cho căn ph&ograve;ng của m&igrave;nh.</p>\n\n<h2>1/ Lựa chọn ph&ugrave; hợp với kh&ocirc;ng gian</h2>\n\n<p>Một chiếc b&agrave;n uống nước được coi l&agrave; ph&ugrave; hợp v&agrave; ho&agrave;n hảo, điều đầu ti&ecirc;n cần phải ph&ugrave; hợp với kh&ocirc;ng gian của căn ph&ograve;ng nơi n&oacute; được trưng b&agrave;y, nghĩa l&agrave; chiếc b&agrave;n kh&ocirc;ng được qu&aacute; to hoặc kh&ocirc;ng qu&aacute; nhỏ m&agrave; cần h&agrave;i h&ograve;a với c&aacute;c vật dụng xung quanh chiếc b&agrave;n đ&oacute;. Điều đ&oacute; c&oacute; nghĩa gia chủ cần t&iacute;nh to&aacute;n, c&acirc;n nhắc rất nhiều trong trường hợp sử dụng c&aacute;c sản phẩm b&agrave;n uống nước được sản xuất c&oacute; sẵn tr&ecirc;n thị trường, để khi mua về chiếc b&agrave;n c&oacute; thể h&agrave;i h&ograve;a với căn ph&ograve;ng.</p>\n\n<h2>2/ Lựa chọn b&agrave;n uống nước ph&ugrave; hợp với m&agrave;u sắc căn ph&ograve;ng.</h2>\n\n<p>Ngo&agrave;i yếu tố ph&ugrave; hợp với kh&ocirc;ng gian căn ph&ograve;ng, m&agrave;u sắc của chiếc b&agrave;n tr&agrave; cũng cần được quan t&acirc;m để kh&ocirc;ng qu&aacute; nổi trội v&agrave; g&acirc;y ch&oacute;i mắt cho gia chủ cũng như bạn b&egrave; khi đến chơi nh&agrave;. Những chiếc b&agrave;n tr&agrave; n&ecirc;n c&oacute; m&agrave;u sắc ấm &aacute;p, nhẹ nh&agrave;ng để tạo cho kh&ocirc;ng gian khi thưởng thức tr&agrave; được thoải m&aacute;i nhất.</p>\n\n<h2>3/ Lựa chọn thiết kế b&agrave;n tr&agrave; ph&ugrave; hợp.</h2>\n\n<p>Với một căn ph&ograve;ng mang phong c&aacute;ch hiện đại, việc sử dụng một chiếc b&agrave;n uống nước cổ điển, truyền thống sẽ l&agrave;m hỏng kh&ocirc;ng gian v&agrave; g&acirc;y nhức mắt. Ch&iacute;nh v&igrave; vậy cần quan t&acirc;m rất lớn cho thiết kế b&agrave;n tr&agrave; khi lựa chọn cho căn ph&ograve;ng của gia đ&igrave;nh để mọi vật h&agrave;i h&ograve;a trong kh&ocirc;ng gian đ&oacute; nhất.&nbsp;</p>\n\n<p>Những lưu &yacute; tưởng trừng như cơ bản ai cũng biết như tr&ecirc;n thực ra đ&atilde; c&oacute; rất nhiều người đ&atilde; v&agrave; đang gặp phải v&agrave; đ&atilde; phải thay thế những chiếc b&agrave;n uống nước kh&aacute;c cho căn ph&ograve;ng để chữa ch&aacute;y những lựa chọn trước đ&oacute; của ch&iacute;nh m&igrave;nh. Một lựa chọn an to&agrave;n cho mọi gia đ&igrave;nh khi lựa chọn c&aacute;c vật dụng nội thất như b&agrave;n uống nước, cầu thang, c&aacute;nh cửa, giường gỗ v&agrave; tủ gỗ,... l&agrave; lựa chọn c&aacute;c xưởng sản xuất uy t&iacute;n, nơi c&oacute; thể c&ugrave;ng cấp những lời tư vấn ph&ugrave; hợp nhất.</p>\n\n<p>&nbsp;</p>\n",
    "image": "http://apixm.devmaster.vn/images/products/phong-khach/001.jpg",
    "metaTitle": "Bàn uống nước",
    "metaKeyword": "Bàn uống nước, bàn trà, bàn uống nước chung cư, bàn trà chung cư",
    "metaDescription": "Bàn uống nước với thiết kế sang trọng, màu sắc tao nhã phù hợp với mọi không gian phòng khách trong các căn hộ chung cư hiện đại. Bàn uống nước tại xưởng mộc Hoàng Hoan được thiết kế bằng chất liệu gỗ nhập khẩu trực tiếp đem đến trải nghiệm tuyệt vời cho ngôi nhà của bạn.\n",
    "slug": "ban-uong-nuoc",
    "priceOld": 8999000,
    "priceNew": 8999000,
    "size": "4 ngăn",
    "views": 0,
    "likes": 0,
    "star": null,
    "home": null,
    "hot": 1,
    "createdDate": "2020-08-26T00:00:00",
    "updatedDate": "2020-08-26T18:53:29.497",
    "adminCreated": "4",
    "adminUpdated": "4",
    "status": 1,
    "isdelete": null
    },
    {
    "id": 10,
    "cid": 8,
    "code": "P003",
    "title": "Giường hộp ",
    "description": "<p>Giường hộp thiết kế sang trọng tiện &iacute;ch</p>\n",
    "content": "<p>Giường hộp thiết kế sang trọng tiện &iacute;ch</p>\n",
    "image": "http://apixm.devmaster.vn/images/products/phong-ngu/003.jpg",
    "metaTitle": "Giường hộp thiết kế sang trọng tiện ích",
    "metaKeyword": "Giường hộp thiết kế sang trọng tiện ích",
    "metaDescription": "Giường hộp thiết kế sang trọng tiện ích",
    "slug": "giuong-hop-thiet-ke-sang-trong-tien-ich",
    "priceOld": 8999000,
    "priceNew": 8999000,
    "size": null,
    "views": 0,
    "likes": 0,
    "star": null,
    "home": 0,
    "hot": null,
    "createdDate": "2020-07-28T00:00:00",
    "updatedDate": "2020-07-28T10:43:56.717",
    "adminCreated": "4",
    "adminUpdated": "4",
    "status": 1,
    "isdelete": null
    },
    {
    "id": 11,
    "cid": 10,
    "code": "P005",
    "title": "Bàn ăn nhà bếp",
    "description": "<p>B&agrave;n ăn nh&agrave; bếp sang trọng</p>\n",
    "content": "<p>B&agrave;n ăn nh&agrave; bếp sang trọng</p>\n",
    "image": "http://apixm.devmaster.vn/images/products/phong-bep/004.jpg",
    "metaTitle": "Bàn ăn nhà bếp sang trọng",
    "metaKeyword": "Bàn ăn nhà bếp sang trọng",
    "metaDescription": "Bàn ăn nhà bếp sang trọng",
    "slug": "ban-an-nha-bep-sang-trong",
    "priceOld": 9870000,
    "priceNew": 9899000,
    "size": null,
    "views": 0,
    "likes": 0,
    "star": null,
    "home": 0,
    "hot": null,
    "createdDate": "2020-07-28T00:00:00",
    "updatedDate": "2020-07-28T10:42:43.207",
    "adminCreated": "4",
    "adminUpdated": "4",
    "status": 1,
    "isdelete": null
    },
    {
    "id": 12,
    "cid": 7,
    "code": "P006",
    "title": "Bàn uống nước 2",
    "description": "<p>B&agrave;n uống nước 2</p>\n",
    "content": "<p>B&agrave;n uống nước 2</p>\n",
    "image": "http://apixm.devmaster.vn/images/products/phong-khach/015.jpg",
    "metaTitle": "BÀN UỐNG NƯỚC 2",
    "metaKeyword": "Bàn uống nước 2",
    "metaDescription": "Bàn uống nước 2\n",
    "slug": "ban-uong-nuoc-2",
    "priceOld": 3999000,
    "priceNew": 3999000,
    "size": "Size vừa",
    "views": 0,
    "likes": 0,
    "star": null,
    "home": null,
    "hot": 1,
    "createdDate": "2020-07-31T00:00:00",
    "updatedDate": "2020-07-31T00:49:13.867",
    "adminCreated": "4",
    "adminUpdated": "4",
    "status": 1,
    "isdelete": null
    },
    {
    "id": 13,
    "cid": 7,
    "code": "P007",
    "title": "Kệ để đồ",
    "description": "<p>Kệ để đồ</p>\n",
    "content": "<p>Kệ để đồ</p>\n",
    "image": "http://apixm.devmaster.vn/images/products/phong-khach/008.jpg",
    "metaTitle": "Kệ để đồ",
    "metaKeyword": "Kệ để đồ",
    "metaDescription": "Kệ để đồ\n",
    "slug": "ke-de-do",
    "priceOld": 15999000,
    "priceNew": 12999000,
    "size": "4 ngăn",
    "views": 0,
    "likes": 0,
    "star": null,
    "home": null,
    "hot": 1,
    "createdDate": "2020-07-31T00:00:00",
    "updatedDate": "2020-07-31T00:50:56.44",
    "adminCreated": "4",
    "adminUpdated": "4",
    "status": 1,
    "isdelete": null
    },
    {
    "id": 14,
    "cid": 7,
    "code": "P008",
    "title": "Kệ TV",
    "description": "<p>Kệ TV</p>\n",
    "content": "<p>Kệ TV</p>\n",
    "image": "http://apixm.devmaster.vn/images/products/phong-khach/002.jpg",
    "metaTitle": "Kệ TV",
    "metaKeyword": "Kệ TV",
    "metaDescription": "Kệ TV\n",
    "slug": "ke-tv",
    "priceOld": 15999000,
    "priceNew": 12899000,
    "size": "4 ngăn",
    "views": 0,
    "likes": 0,
    "star": null,
    "home": null,
    "hot": 1,
    "createdDate": "2020-07-31T00:50:35.453",
    "updatedDate": "2020-07-31T00:50:35.453",
    "adminCreated": "4",
    "adminUpdated": "4",
    "status": 1,
    "isdelete": null
    },
    {
    "id": 15,
    "cid": 8,
    "code": "P009",
    "title": "Tủ quần áo",
    "description": "<p>Tủ quần &aacute;o</p>\n",
    "content": "<p>Tủ quần &aacute;o</p>\n",
    "image": "http://apixm.devmaster.vn/images/products/phong-ngu/007.jpg",
    "metaTitle": "Tủ quần áo",
    "metaKeyword": "Tủ quần áo",
    "metaDescription": "Tủ quần áo\n",
    "slug": "tu-quan-ao",
    "priceOld": 15999000,
    "priceNew": 12999000,
    "size": "4 ngăn, trắng, gỗ",
    "views": 0,
    "likes": 0,
    "star": null,
    "home": null,
    "hot": 1,
    "createdDate": "2020-07-31T00:55:32.307",
    "updatedDate": "2020-07-31T00:55:32.307",
    "adminCreated": "4",
    "adminUpdated": "4",
    "status": 1,
    "isdelete": null
    },
    {
    "id": 17,
    "cid": 8,
    "code": "P010",
    "title": "Giường gỗ",
    "description": "<p>Giường gỗ</p>\n",
    "content": "<p>Giường gỗ</p>\n",
    "image": "http://apixm.devmaster.vn/images/products/phong-ngu/003.jpg",
    "metaTitle": "Giường gỗ",
    "metaKeyword": "Giường gỗ",
    "metaDescription": "Giường gỗ\n",
    "slug": "giuong-go",
    "priceOld": 20999000,
    "priceNew": 18999000,
    "size": "Size vừa",
    "views": 0,
    "likes": 0,
    "star": null,
    "home": null,
    "hot": 1,
    "createdDate": "2020-07-31T00:00:00",
    "updatedDate": "2020-07-31T01:15:39.39",
    "adminCreated": "4",
    "adminUpdated": "4",
    "status": 1,
    "isdelete": null
    },
    {
    "id": 18,
    "cid": 8,
    "code": "P011",
    "title": "Kệ đầu giường",
    "description": "<p>Kệ đầu giường</p>\n",
    "content": "<p>Kệ đầu giường</p>\n",
    "image": "http://apixm.devmaster.vn/images/products/phong-ngu/004.jpg",
    "metaTitle": "Kệ đầu giường",
    "metaKeyword": "Kệ đầu giường",
    "metaDescription": "Kệ đầu giường\n",
    "slug": "ke-dau-giuong",
    "priceOld": 20899000,
    "priceNew": 18899000,
    "size": "2 ngăn",
    "views": 0,
    "likes": 0,
    "star": null,
    "home": null,
    "hot": 1,
    "createdDate": "2020-07-31T00:00:00",
    "updatedDate": "2020-07-31T01:16:27.333",
    "adminCreated": "4",
    "adminUpdated": "4",
    "status": 1,
    "isdelete": null
    },
    {
    "id": 19,
    "cid": 8,
    "code": "P012",
    "title": "Giường châu âu",
    "description": "<h1>GIƯỜNG NGỦ T&Acirc;N CỔ ĐIỂN</h1>\n\n<p>Đối với kh&ocirc;ng gian ph&ograve;ng ngủ th&igrave; nội thất quan trọng v&agrave; được quan t&acirc;m nhiều nhất ch&iacute;nh l&agrave; chiếc giường ngủ. Giờ đ&acirc;y chiếc giường ngủ kh&ocirc;ng đơn giản l&agrave; nơi để con người nghỉ ngơi m&agrave; c&ograve;n g&oacute;p phần l&agrave;m n&ecirc;n vẻ đẹp cho kh&ocirc;ng gian sống ri&ecirc;ng tư n&agrave;y. Nếu bạn đang sở hữu ph&ograve;ng ngủ kiển tr&uacute;c t&acirc;n cổ điển th&igrave; chiếc giường ngủ đồng h&agrave;nh ph&ugrave; hợp nhất</p>\n",
    "content": "<h1>GIƯỜNG NGỦ T&Acirc;N CỔ ĐIỂN</h1>\n\n<p>Đối với kh&ocirc;ng gian ph&ograve;ng ngủ th&igrave; nội thất quan trọng v&agrave; được quan t&acirc;m nhiều nhất ch&iacute;nh l&agrave; chiếc giường ngủ. Giờ đ&acirc;y chiếc giường ngủ kh&ocirc;ng đơn giản l&agrave; nơi để con người nghỉ ngơi m&agrave; c&ograve;n g&oacute;p phần l&agrave;m n&ecirc;n vẻ đẹp cho kh&ocirc;ng gian sống ri&ecirc;ng tư n&agrave;y. Nếu bạn đang sở hữu ph&ograve;ng ngủ kiển tr&uacute;c t&acirc;n cổ điển th&igrave; chiếc giường ngủ đồng h&agrave;nh ph&ugrave; hợp nhất</p>\n\n<h1>GIƯỜNG NGỦ T&Acirc;N CỔ ĐIỂN</h1>\n\n<p>Đối với kh&ocirc;ng gian ph&ograve;ng ngủ th&igrave; nội thất quan trọng v&agrave; được quan t&acirc;m nhiều nhất ch&iacute;nh l&agrave; chiếc giường ngủ. Giờ đ&acirc;y chiếc giường ngủ kh&ocirc;ng đơn giản l&agrave; nơi để con người nghỉ ngơi m&agrave; c&ograve;n g&oacute;p phần l&agrave;m n&ecirc;n vẻ đẹp cho kh&ocirc;ng gian sống ri&ecirc;ng tư n&agrave;y. Nếu bạn đang sở hữu ph&ograve;ng ngủ kiển tr&uacute;c t&acirc;n cổ điển th&igrave; chiếc giường ngủ đồng h&agrave;nh ph&ugrave; hợp nhất</p>\n\n<h1>GIƯỜNG NGỦ T&Acirc;N CỔ ĐIỂN</h1>\n\n<p>Đối với kh&ocirc;ng gian ph&ograve;ng ngủ th&igrave; nội thất quan trọng v&agrave; được quan t&acirc;m nhiều nhất ch&iacute;nh l&agrave; chiếc giường ngủ. Giờ đ&acirc;y chiếc giường ngủ kh&ocirc;ng đơn giản l&agrave; nơi để con người nghỉ ngơi m&agrave; c&ograve;n g&oacute;p phần l&agrave;m n&ecirc;n vẻ đẹp cho kh&ocirc;ng gian sống ri&ecirc;ng tư n&agrave;y. Nếu bạn đang sở hữu ph&ograve;ng ngủ kiển tr&uacute;c t&acirc;n cổ điển th&igrave; chiếc giường ngủ đồng h&agrave;nh ph&ugrave; hợp nhất</p>\n\n<h1>GIƯỜNG NGỦ T&Acirc;N CỔ ĐIỂN</h1>\n\n<p>Đối với kh&ocirc;ng gian ph&ograve;ng ngủ th&igrave; nội thất quan trọng v&agrave; được quan t&acirc;m nhiều nhất ch&iacute;nh l&agrave; chiếc giường ngủ. Giờ đ&acirc;y chiếc giường ngủ kh&ocirc;ng đơn giản l&agrave; nơi để con người nghỉ ngơi m&agrave; c&ograve;n g&oacute;p phần l&agrave;m n&ecirc;n vẻ đẹp cho kh&ocirc;ng gian sống ri&ecirc;ng tư n&agrave;y. Nếu bạn đang sở hữu ph&ograve;ng ngủ kiển tr&uacute;c t&acirc;n cổ điển th&igrave; chiếc giường ngủ đồng h&agrave;nh ph&ugrave; hợp nhất</p>\n\n<h1>GIƯỜNG NGỦ T&Acirc;N CỔ ĐIỂN</h1>\n\n<p>Đối với kh&ocirc;ng gian ph&ograve;ng ngủ th&igrave; nội thất quan trọng v&agrave; được quan t&acirc;m nhiều nhất ch&iacute;nh l&agrave; chiếc giường ngủ. Giờ đ&acirc;y chiếc giường ngủ kh&ocirc;ng đơn giản l&agrave; nơi để con người nghỉ ngơi m&agrave; c&ograve;n g&oacute;p phần l&agrave;m n&ecirc;n vẻ đẹp cho kh&ocirc;ng gian sống ri&ecirc;ng tư n&agrave;y. Nếu bạn đang sở hữu ph&ograve;ng ngủ kiển tr&uacute;c t&acirc;n cổ điển th&igrave; chiếc giường ngủ đồng h&agrave;nh ph&ugrave; hợp nhất</p>\n",
    "image": "http://apixm.devmaster.vn/images/products/phong-ngu/013.jpg",
    "metaTitle": "Giường châu âu giá tốt tại hà nội",
    "metaKeyword": "Giường châu âu",
    "metaDescription": "GIƯỜNG NGỦ TÂN CỔ ĐIỂN\n\nĐối với không gian phòng ngủ thì nội thất quan trọng và được quan tâm nhiều nhất chính là chiếc giường ngủ. Giờ đây chiếc giường ngủ không đơn giản là nơi để con người nghỉ ngơi mà còn góp phần làm nên vẻ đẹp cho không gian sống riêng tư này. Nếu bạn đang sở hữu phòng ngủ kiển trúc tân cổ điển thì chiếc giường ngủ đồng hành phù hợp nhất\n",
    "slug": "giuong-chau-au-gia-tot",
    "priceOld": 25999000,
    "priceNew": 22999000,
    "size": "Size vừa",
    "views": 0,
    "likes": 0,
    "star": null,
    "home": null,
    "hot": 1,
    "createdDate": "2020-08-10T00:00:00",
    "updatedDate": "2020-08-10T14:58:46.003",
    "adminCreated": "4",
    "adminUpdated": "4",
    "status": 1,
    "isdelete": null
    },
    {
    "id": 20,
    "cid": 7,
    "code": "P013",
    "title": "SOFA",
    "description": "SOFA",
    "content": "SOFA",
    "image": "http://apixm.devmaster.vn/images/products/phong-khach/011.jpg",
    "metaTitle": "SOFA",
    "metaKeyword": "SOFA",
    "metaDescription": "SOFA",
    "slug": "sofa",
    "priceOld": 10000000,
    "priceNew": 8400000,
    "size": null,
    "views": null,
    "likes": null,
    "star": null,
    "home": 0,
    "hot": null,
    "createdDate": "2023-09-30T16:24:25.493",
    "updatedDate": "2023-09-30T16:24:25.493",
    "adminCreated": "4",
    "adminUpdated": "4",
    "status": 1,
    "isdelete": false
    },
    {
    "id": 21,
    "cid": 7,
    "code": "P014",
    "title": "Bàn trà",
    "description": "Bàn trà",
    "content": "Bàn trà",
    "image": "http://apixm.devmaster.vn/images/products/phong-khach/009.jpg",
    "metaTitle": "Bàn trà",
    "metaKeyword": "Bàn trà",
    "metaDescription": "Bàn trà",
    "slug": null,
    "priceOld": 25999000,
    "priceNew": 22999000,
    "size": null,
    "views": null,
    "likes": null,
    "star": null,
    "home": 0,
    "hot": null,
    "createdDate": "2023-09-30T16:28:22.943",
    "updatedDate": "2023-09-30T16:28:22.943",
    "adminCreated": "4",
    "adminUpdated": "4",
    "status": 1,
    "isdelete": false
    },
    {
    "id": 22,
    "cid": 11,
    "code": "P015",
    "title": "Bồn rửa mặt",
    "description": "Bồn rửa mặt",
    "content": "Bồn rửa mặt",
    "image": "http://apixm.devmaster.vn/images/products/phong-tam/005.jpg",
    "metaTitle": "Bồn rửa mặt",
    "metaKeyword": "Bồn rửa mặt",
    "metaDescription": "Bồn rửa mặt",
    "slug": null,
    "priceOld": 8500000,
    "priceNew": 8000000,
    "size": null,
    "views": null,
    "likes": null,
    "star": null,
    "home": 0,
    "hot": null,
    "createdDate": "2023-09-30T16:43:15.333",
    "updatedDate": "2023-09-30T16:43:15.333",
    "adminCreated": "4",
    "adminUpdated": "4",
    "status": 1,
    "isdelete": false
    },
    {
    "id": 23,
    "cid": 11,
    "code": "P016",
    "title": "Bồn rừa tay",
    "description": "Bồn rừa tay",
    "content": "Bồn rừa tay",
    "image": "http://apixm.devmaster.vn/images/products/phong-tam/006.jpg",
    "metaTitle": "Bồn rừa tay",
    "metaKeyword": "Bồn rừa tay",
    "metaDescription": "Bồn rừa tay",
    "slug": "bon-rua-tay",
    "priceOld": 3950000,
    "priceNew": 3900000,
    "size": null,
    "views": null,
    "likes": null,
    "star": null,
    "home": 0,
    "hot": null,
    "createdDate": "2023-09-30T16:44:40.917",
    "updatedDate": "2023-09-30T16:44:40.917",
    "adminCreated": "4",
    "adminUpdated": "4",
    "status": 1,
    "isdelete": false
    },
    {
    "id": 24,
    "cid": 11,
    "code": "P017",
    "title": "Tủ âm tường",
    "description": "Tủ âm tường",
    "content": "Tủ âm tường",
    "image": "http://apixm.devmaster.vn/images/products/phong-tam/007.jpg",
    "metaTitle": "Tủ âm tường",
    "metaKeyword": "Tủ âm tường",
    "metaDescription": "Tủ âm tường",
    "slug": "tu-am-tuong-p017",
    "priceOld": 9500000,
    "priceNew": 8900000,
    "size": null,
    "views": null,
    "likes": null,
    "star": null,
    "home": 0,
    "hot": null,
    "createdDate": "2023-09-30T16:46:15.97",
    "updatedDate": "2023-09-30T16:46:15.97",
    "adminCreated": "4",
    "adminUpdated": "4",
    "status": 1,
    "isdelete": false
    },
    {
    "id": 25,
    "cid": 11,
    "code": "P018",
    "title": "Bồn rửa 2",
    "description": "Bồn rửa 2",
    "content": "Bồn rửa 2",
    "image": "http://apixm.devmaster.vn/images/products/phong-tam/008.jpg",
    "metaTitle": "Bồn rửa 2",
    "metaKeyword": "Bồn rửa 2",
    "metaDescription": "Bồn rửa 2",
    "slug": "bon-rua-2-p018",
    "priceOld": 4000000,
    "priceNew": 3300000,
    "size": null,
    "views": null,
    "likes": null,
    "star": null,
    "home": 0,
    "hot": null,
    "createdDate": "2023-09-30T16:46:59.757",
    "updatedDate": "2023-09-30T16:46:59.757",
    "adminCreated": "4",
    "adminUpdated": "4",
    "status": 1,
    "isdelete": false
    },
    {
    "id": 26,
    "cid": 12,
    "code": "P019",
    "title": "Giường tầng",
    "description": "Giường tầng",
    "content": "Giường tầng",
    "image": "http://apixm.devmaster.vn/images/products/tre-em/016.jpg",
    "metaTitle": "Giường tầng",
    "metaKeyword": "Giường tầng",
    "metaDescription": "Giường tầng",
    "slug": "giuong-tang-p019",
    "priceOld": 11000000,
    "priceNew": 9800000,
    "size": null,
    "views": null,
    "likes": null,
    "star": null,
    "home": 0,
    "hot": null,
    "createdDate": "2023-09-30T16:50:35.72",
    "updatedDate": "2023-09-30T16:50:35.72",
    "adminCreated": "4",
    "adminUpdated": "4",
    "status": 1,
    "isdelete": false
    },
    {
    "id": 27,
    "cid": 12,
    "code": "P020",
    "title": "Bàn học",
    "description": "Bàn học",
    "content": "Bàn học",
    "image": "http://apixm.devmaster.vn/images/products/tre-em/017.jpg",
    "metaTitle": "Bàn học",
    "metaKeyword": "Bàn học",
    "metaDescription": "Bàn học",
    "slug": "ban-hoc-p020",
    "priceOld": 3500000,
    "priceNew": 3000000,
    "size": null,
    "views": null,
    "likes": null,
    "star": null,
    "home": 0,
    "hot": null,
    "createdDate": "2023-09-30T16:51:20.29",
    "updatedDate": "2023-09-30T16:51:20.29",
    "adminCreated": "4",
    "adminUpdated": "4",
    "status": 1,
    "isdelete": false
    },
    {
    "id": 28,
    "cid": 13,
    "code": "P021",
    "title": "Ghế văn phòng",
    "description": "Ghế văn phòng",
    "content": "Ghế văn phòng",
    "image": "http://apixm.devmaster.vn/images/products/tre-em/018.jpg",
    "metaTitle": "Ghế văn phòng",
    "metaKeyword": "Ghế văn phòng",
    "metaDescription": "Ghế văn phòng",
    "slug": "ghe-van-phong-p021",
    "priceOld": 6000000,
    "priceNew": 5700000,
    "size": null,
    "views": null,
    "likes": null,
    "star": null,
    "home": 0,
    "hot": null,
    "createdDate": "2023-09-30T16:58:15.04",
    "updatedDate": "2023-09-30T16:58:15.04",
    "adminCreated": "4",
    "adminUpdated": "4",
    "status": 1,
    "isdelete": false
    },
    {
    "id": 29,
    "cid": 15,
    "code": "P022",
    "title": "Đèn chùm",
    "description": "Đèn chùm",
    "content": "Đèn chùm",
    "image": "http://apixm.devmaster.vn/images/products/do-trang-tri/020.jpg",
    "metaTitle": "Đèn chùm",
    "metaKeyword": "Đèn chùm",
    "metaDescription": "Đèn chùm",
    "slug": "den-chum-p022",
    "priceOld": 5300000,
    "priceNew": 4300000,
    "size": null,
    "views": null,
    "likes": null,
    "star": null,
    "home": 0,
    "hot": null,
    "createdDate": "2023-09-30T17:00:32.483",
    "updatedDate": "2023-09-30T17:00:32.483",
    "adminCreated": "4",
    "adminUpdated": "4",
    "status": 1,
    "isdelete": false
    },
    {
    "id": 30,
    "cid": 14,
    "code": "P023",
    "title": "Cầu thang",
    "description": "Cầu thang",
    "content": "Cầu thang",
    "image": "http://apixm.devmaster.vn/images/products/cau-thang/019.jpg",
    "metaTitle": "Cầu thang",
    "metaKeyword": "Cầu thang",
    "metaDescription": "Cầu thang",
    "slug": "cau-thang-p023",
    "priceOld": 35000000,
    "priceNew": 30000000,
    "size": null,
    "views": null,
    "likes": null,
    "star": null,
    "home": 0,
    "hot": null,
    "createdDate": "2023-09-30T17:08:24.57",
    "updatedDate": "2023-09-30T17:08:24.57",
    "adminCreated": "4",
    "adminUpdated": "4",
    "status": 1,
    "isdelete": false
    },
]